function [y1] = myNeuralNetworkFunctionForY1_871(x1)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 07-Dec-2014 02:49:33.
% 
% [y1] = myNeuralNetworkFunction(x1) takes these arguments:
%   x = 3xQ matrix, input #1
% and returns:
%   y = 1xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

  % ===== NEURAL NETWORK CONSTANTS =====
  
  % Input 1
  x1_step1_xoffset = [0;-1;0.629776921099141];
  x1_step1_gain = [2;1;8.41263392011976];
  x1_step1_ymin = -1;
  
  % Layer 1
  b1 = [-2.5123105775080079;1.7376147624662082;-1.0312136320319225;-2.8712423174301716];
  IW1_1 = [1.7647007852107357 0 -2.8942655671824022;-1.3742304110289749 0 1.9560952294431346;-2.2780792071609306 0 -1.6939337060442272;-2.3162327721765656 0 1.449020555074594];
  
  % Layer 2
  b2 = 0.24394808486542163;
  LW2_1 = [0.19229717216506098 0.14680781088249839 0.20337504973995435 -0.94676930400015713];
  
  % Output 1
  y1_step1_ymin = -1;
  y1_step1_gain = 2.14792738463867;
  y1_step1_xoffset = 0;
  
  % ===== SIMULATION ========
  
  % Dimensions
  Q = size(x1,2); % samples
  
  % Input 1
  xp1 = mapminmax_apply(x1,x1_step1_gain,x1_step1_xoffset,x1_step1_ymin);
  
  % Layer 1
  a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*xp1);
  
  % Layer 2
  a2 = repmat(b2,1,Q) + LW2_1*a1;
  
  % Output 1
  y1 = mapminmax_reverse(a2,y1_step1_gain,y1_step1_xoffset,y1_step1_ymin);
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings_gain,settings_xoffset,settings_ymin)
  y = bsxfun(@minus,x,settings_xoffset);
  y = bsxfun(@times,y,settings_gain);
  y = bsxfun(@plus,y,settings_ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings_gain,settings_xoffset,settings_ymin)
  x = bsxfun(@minus,y,settings_ymin);
  x = bsxfun(@rdivide,x,settings_gain);
  x = bsxfun(@plus,x,settings_xoffset);
end
