function [Number,TimeStamp,AccVoltage,Crankshaft,Additionalgeneratorpower,Consumptionpower,Gridvoltage,Fuel,Accvoltage,Fuel2,Grid2,Acc2] = importData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [NUMBER,TIMESTAMP,ACCVOLTAGE,CRANKSHAFT,ADDITIONALGENERATORPOWER,CONSUMPTIONPOWER,GRIDVOLTAGE,FUEL,ACCVOLTAGE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [NUMBER,TIMESTAMP,ACCVOLTAGE,CRANKSHAFT,ADDITIONALGENERATORPOWER,CONSUMPTIONPOWER,GRIDVOLTAGE,FUEL,ACCVOLTAGE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Number,TimeStamp,AccVoltage,Crankshaft,Additionalgeneratorpower,Consumptionpower,Gridvoltage,Fuel,Accvoltage] = importfile('InputData.csv',2, 1314);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/12/26 15:23:56

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Number = dataArray{:, 1};
TimeStamp = dataArray{:, 2};
AccVoltage = dataArray{:, 3};
Crankshaft = dataArray{:, 4};
Additionalgeneratorpower = dataArray{:, 5};
Consumptionpower = dataArray{:, 6};
Gridvoltage = dataArray{:, 7};
Fuel = dataArray{:, 8};
Accvoltage = dataArray{:, 9};
Fuel2 =dataArray{:, 10};
Grid2=dataArray{:, 11};
Acc2 =dataArray{:, 12};

